import EarthCanvas from "./Earth";
import BallCanvas from "./Ball";
import ComputersCanvas from "./Computers";
import StarsCanvas from "./StarsCanvas";
import About  from "./About";
import Contact from "./Contact";
import Experience from "./Experience";
import Feedbacks from "./Feedbacks";
import Navbar from "./Navbar";
import Tech from "./Tech";
import Works from "./Works";
import Hero from "./Hero";
import Loader from "./Loader";
export { EarthCanvas, BallCanvas,Contact,Feedbacks,Experience, ComputersCanvas, StarsCanvas,About,Tech,Works, Hero, Loader,Navbar};
